#pragma once
// clang-format off

/*
		wemos_v3_map.h
		Part of Grbl_ESP32

	   Protoneer CNC Shield with ESPduino board
	   

		2025    - Asemproject 
*/

#define MACHINE_NAME "WEMOS_ESP32_PROTONEER_V3"

#define X_STEP_PIN      		GPIO_NUM_26
#define X_DIRECTION_PIN  		GPIO_NUM_16
#define X_RMT_CHANNEL			0

#define Y_STEP_PIN      		GPIO_NUM_25
#define Y_DIRECTION_PIN   	    GPIO_NUM_27
#define Y_RMT_CHANNEL			1

#define Z_STEP_PIN      		GPIO_NUM_17
#define Z_DIRECTION_PIN   	    GPIO_NUM_14
#define Z_RMT_CHANNEL			2		

#define STEPPERS_DISABLE_PIN GPIO_NUM_12

#define X_LIMIT_PIN      		GPIO_NUM_13
#define Y_LIMIT_PIN      		GPIO_NUM_5
#define Z_LIMIT_PIN     		GPIO_NUM_23
#define LIMIT_MASK      		0b111

#define PROBE_PIN       		GPIO_NUM_39

#define SPINDLE_ENABLE_PIN    GPIO_NUM_19

#define SD_SPI_SCK_PIN     GPIO_NUM_22
#define SD_SPI_MOSI_PIN    GPIO_NUM_21
#define SD_SPI_MISO_PIN    GPIO_NUM_34
#define SD_CARD_CS_PIN     GPIO_NUM_33

#define SPINDLE_DIR_PIN		GPIO_NUM_18

#define CONTROL_RESET_PIN         GPIO_NUM_2
#define CONTROL_FEED_HOLD_PIN     GPIO_NUM_4

// defaults
#define DEFAULT_STEP_PULSE_MICROSECONDS 10
#define DEFAULT_STEPPER_IDLE_LOCK_TIME 250

#define DEFAULT_STEPPING_INVERT_MASK 0
#define DEFAULT_DIRECTION_INVERT_MASK 0
#define DEFAULT_INVERT_ST_ENABLE 0

// limit & probe: wired to ground (active-low / NC recommended)
#define DEFAULT_INVERT_LIMIT_PINS 1
#define DEFAULT_INVERT_PROBE_PIN 1

#define DEFAULT_STATUS_REPORT_MASK 1

#define DEFAULT_JUNCTION_DEVIATION 0.01
#define DEFAULT_ARC_TOLERANCE 0.002
#define DEFAULT_REPORT_INCHES 0

#define DEFAULT_SOFT_LIMIT_ENABLE 0
#define DEFAULT_HARD_LIMIT_ENABLE 1

#define DEFAULT_HOMING_ENABLE 1
// Homing dir mask: bit0 = X, bit1 = Y, bit2 = Z (X-, Y-, Z+)
#define DEFAULT_HOMING_DIR_MASK 0b011
#define DEFAULT_HOMING_FEED_RATE 25.0
#define DEFAULT_HOMING_SEEK_RATE 500.0
#define DEFAULT_HOMING_DEBOUNCE_DELAY 250
#define DEFAULT_HOMING_PULLOFF 3.0

#define DEFAULT_LASER_MODE 0

#define DEFAULT_X_STEPS_PER_MM 200.0
#define DEFAULT_Y_STEPS_PER_MM 200.0
#define DEFAULT_Z_STEPS_PER_MM 200.0

#define DEFAULT_X_MAX_RATE 1500.0
#define DEFAULT_Y_MAX_RATE 1500.0
#define DEFAULT_Z_MAX_RATE 600.0

#define DEFAULT_X_ACCELERATION 30.0
#define DEFAULT_Y_ACCELERATION 30.0
#define DEFAULT_Z_ACCELERATION 15.0

#define DEFAULT_X_MAX_TRAVEL 279.0
#define DEFAULT_Y_MAX_TRAVEL 526.0
#define DEFAULT_Z_MAX_TRAVEL 97.0
